
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: modeloregersion:latest
    container_name: modeloregresion
    ports:
      - "5001:5001"
    env_file:
      - .env